Initiation/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Initiation.Models;

namespace Initiation.Controllers
{
    public class FormController : Controller
    {
        public ActionResult Form()
        {
            Yo();
            return View();
        }

        [HttpPost] //Envoi du formulaire
        public ActionResult Form(FormModel model)
        {
            Yo();
            if (ModelState.IsValid)
            {
                TempData["info"] = "Votre commentaire à été envoyé!";
                return RedirectToAction("Index", "Home");
            }
            else
                return View();

        }

        private void Yo()
        {
            ViewBag.ImgUrl = "http://www.publicdomainpictures.net/pictures/50000/nahled/smiley-silhouette.jpg";
            ViewBag.Message1 = "Yo";
            ViewData["Message2"] = "What's up?";
        }

    }
}

Initiation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mon application ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Mon logo ici?", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                            <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("<-----Menteur! C'est par ici pour contacter!", "Form", "Form")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @if (TempData["info"] != null)
                {
                    <h2>@TempData["info"]</h2>
                }
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Mon application ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>